<a href="https://colab.research.google.com/github/hasinikondle/DataScience_Task/blob/main/CLEANING_TASK.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns


In [ ]:
df = pd.read_csv("https://github.com/Taj1920/Data-Analysis-Datasets/raw/refs/heads/main/Datasets-Cleaning/USA_presidents.csv")
df.head()

,Unnamed: 0.1,Unnamed: 0,S.No.,president,prior,party,vice,salary,date updated,date created
0,0,0,1,George Washington,Commander-in-Chief of the Continental Army ...,Nonpartisan,John Adams,NaN,2021-07-14,2012-03-04
1,1,1,2,john adams,1st Vice President of the United States,NaN,Thomas Jefferson,"$10,0,00",2021-07-14,2012-03-04
2,2,2,3,NaN,2nd Vice President of the United States,Democratic- Republican,Aaron Burr,NaN,2021-07-14,2012-03-04
3,3,3,4,James Madison,5th United States Secretary of State (1801â...,NaN,George Clinton,"$20,0,00",2021-07-14,NaN
4,4,4,5,NaN,7th United States Secretary of State (1811â...,Democratic- Republican,Daniel D. Tompkins,"$25,0,00",NaN,2012-03-04


In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 47 entries, 0 to 46
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype 
---  ------        --------------  ----- 
 0   Unnamed: 0.1  47 non-null     int64 
 1   Unnamed: 0    47 non-null     int64 
 2   S.No.         47 non-null     int64 
 3   president     45 non-null     object
 4   prior         47 non-null     object
 5   party         45 non-null     object
 6   vice          47 non-null     object
 7   salary        45 non-null     object
 8   date updated  46 non-null     object
 9   date created  46 non-null     object
dtypes: int64(3), object(7)
memory usage: 3.8+ KB


In [ ]:
df.isnull().sum()

,0
Unnamed: 0.1,0
Unnamed: 0,0
S.No.,0
president,2
prior,0
party,2
vice,0
salary,2
date updated,1
date created,1


In [ ]:
df.shape

(47, 10)

In [ ]:
df.dropna(inplace=True) #removing null values

In [ ]:
df.shape

(42, 10)

In [ ]:
df.isnull().sum()

,0
Unnamed: 0.1,0
Unnamed: 0,0
S.No.,0
president,0
prior,0
party,0
vice,0
salary,0
date updated,0
date created,0


In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 42 entries, 5 to 46
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype 
---  ------        --------------  ----- 
 0   Unnamed: 0.1  42 non-null     int64 
 1   Unnamed: 0    42 non-null     int64 
 2   S.No.         42 non-null     int64 
 3   president     42 non-null     object
 4   prior         42 non-null     object
 5   party         42 non-null     object
 6   vice          42 non-null     object
 7   salary        42 non-null     object
 8   date updated  42 non-null     object
 9   date created  42 non-null     object
dtypes: int64(3), object(7)
memory usage: 3.6+ KB


In [ ]:
# removing unwanted columns
df = df.drop("Unnamed: 0.1",axis=1)


In [ ]:
df = df.drop("Unnamed: 0",axis=1)

In [ ]:
# removing duplicate rows
df.shape #42
df.drop_duplicates(inplace=True)
df.shape #41

(41, 8)

In [ ]:
df

,S.No.,president,prior,party,vice,salary,date updated,date created
5,6,John Quincy Adams,8th United States Secretary of State (1817â...,Democratic- Republican,John C. Calhoun,"$30,0,00",2021-07-14,2012-03-04
6,7,Andrew Jackson,U.S. Senator ( Class 2 ) from Tennessee ...,Democratic,John C. Calhoun,"$35,0,00",2021-07-14,2012-03-04
7,8,Martin Van Buren,8th Vice President of the United States,Democratic,Richard Mentor Johnson,"$40,0,00",2021-07-14,2012-03-04
8,9,William Henry Harrison,United States Minister to Colombia (1828–1...,Whig,John Tyler,"$45,0,00",2021-07-14,2012-03-04
9,10,john tyler,10th Vice President of the United States,"Whig April 4, 1841 – September 13, 1841",Office vacant,"$50,0,00",2021-07-14,2012-03-04
10,11,James K. Polk,9th Governor of Tennessee (1839–1841),Democratic,George M. Dallas,"$55,0,00",2021-07-14,2012-03-04
11,12,Zachary Taylor,Major General of the 1st Infantry Regiment ...,Whig,Millard Fillmore,"$60,0,00",2021-07-14,2012-03-04
12,13,Millard Fillmore,12th Vice President of the United States,Whig,Office vacant,"$65,0,00",2021-07-14,2012-03-04
13,14,Franklin Pierce,Brigadier General of the 9th Infantry Unit...,Democratic,William R. King,"$75,0,00",2021-07-14,2012-03-04
14,15,James Buchanan,United States Minister to the Court of St J...,Democratic,John C. Breckinridge,"$85,0,00",2021-07-14,2012-03-04


In [ ]:
# df.info()
df["S.No."].unique()


array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22,
       23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39,
       40, 41, 42, 43, 44, 45])

In [ ]:
# handling s.no. column
df["S.No."] = range(1, len(df) + 1)

In [ ]:
df["S.No."].unique()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41])

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 41 entries, 5 to 46
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype 
---  ------        --------------  ----- 
 0   S.No.         41 non-null     int64 
 1   president     41 non-null     object
 2   prior         41 non-null     object
 3   party         41 non-null     object
 4   vice          41 non-null     object
 5   salary        41 non-null     object
 6   date updated  41 non-null     object
 7   date created  41 non-null     object
dtypes: int64(1), object(7)
memory usage: 3.9+ KB


In [ ]:
df["president"].unique()
df["president"] = df["president"].str.title()

In [ ]:
df["prior"].unique()

array(['8th  United States Secretary of State   (1817–1825)',
       'U.S. Senator   ( Class 2 )   from  Tennessee   (1823–1825)',
       '8th  Vice President of the United States',
       'United States Minister to Colombia   (1828–1829)',
       '10th  Vice President of the United States',
       '9th  Governor of Tennessee   (1839–1841)',
       'Major General  of the  1st Infantry Regiment   United States Army   (1846–1849)',
       '12th  Vice President of the United States',
       'Brigadier General  of the  9th Infantry   United States Army   (1847–1848)',
       "United States Minister  to the   Court of St James's   (1853–1856)",
       "U.S. Representative  for  Illinois' 7th District   (1847–1849)",
       '16th  Vice President of the United States',
       'Commanding General  of the U.S. Army   ( 1864–1869 )',
       '29th & 32nd  Governor of Ohio   (1868–1872 & 1876–1877)',
       "U.S. Representative  for  Ohio's 19th District   (1863–1881)",
   

In [ ]:
df["party"].unique()

array(['Democratic-  Republican', 'Democratic', 'Whig',
       'Whig   April 4, 1841  –  September 13, 1841', 'Republican',
       'Demorcatic', 'Republicans'], dtype=object)

In [ ]:
# handling party column
df["party"] = df["party"].replace({
    "Demorcatic": "Democratic",
    "Republicans": "Republican"
})

In [ ]:
df["party"] = df["party"].str.replace(
    "Whig   April 4, 1841  –  September 13, 1841",
    "Whig"
)

In [ ]:
df["party"] = df["party"].replace(
    "Democratic-  Republican",
    "Democratic-Republican"
)

In [ ]:
df["party"].unique()

array(['Democratic-Republican', 'Democratic', 'Whig', 'Republican'],
      dtype=object)

In [ ]:
df["vice"].unique()

array(['John C. Calhoun', 'John C.     Calhoun', 'Richard Mentor Johnson',
       'John Tyler', 'Office vacant', 'George         M. Dallas',
       '               Millard Fillmore', 'William R. King',
       'John C. Breckinridge', 'Hannibal Hamlin', 'Schuyler Colfax',
       'William A. Wheeler', 'Chester A. Arthur', 'Thomas A. Hendricks',
       'Levi P. Morton', 'Adlai Stevenson', 'Garret Hobart',
       'James S. Sherman', 'Thomas R. Marshall', 'Calvin Coolidge',
       'Charles Curtis', 'John Nance Garner', 'Richard Nixon',
       'Lyndon B. Johnson', 'Spiro Agnew', 'Walter Mondale',
       'George H. W. Bush', 'Dan Quayle', 'Al Gore', 'Dick Cheney',
       'Joe Biden', 'Mike Pence'], dtype=object)

In [ ]:
df.rename(columns={"vice": "vice_president"}, inplace=True)

In [ ]:
df["vice_president"].str.strip()
df["vice_president"] = df["vice_president"].str.split().str.join(" ")
df["vice_president"].unique()

array(['John C. Calhoun', 'Richard Mentor Johnson', 'John Tyler',
       'Office vacant', 'George M. Dallas', 'Millard Fillmore',
       'William R. King', 'John C. Breckinridge', 'Hannibal Hamlin',
       'Schuyler Colfax', 'William A. Wheeler', 'Chester A. Arthur',
       'Thomas A. Hendricks', 'Levi P. Morton', 'Adlai Stevenson',
       'Garret Hobart', 'James S. Sherman', 'Thomas R. Marshall',
       'Calvin Coolidge', 'Charles Curtis', 'John Nance Garner',
       'Richard Nixon', 'Lyndon B. Johnson', 'Spiro Agnew',
       'Walter Mondale', 'George H. W. Bush', 'Dan Quayle', 'Al Gore',
       'Dick Cheney', 'Joe Biden', 'Mike Pence'], dtype=object)

In [ ]:
df["salary"].unique()

array(['$30,0,00', '$35,0,00', '$40,0,00', '$45,0,00', '$50,0,00',
       '$55,0,00', '$60,0,00', '$65,0,00', '$75,0,00', '$85,0,00',
       '$95,0,00', '$10,5,000', '$11,5,000', '$12,5,000', '$13,5,000',
       '$14,5,000', '$15,5,000', '$16,5,000', '$17,5,000', '$18,5,000',
       '$19,5,000', '$20,5,000', '$22,5,000', '$23,5,000', '$24,5,000',
       '$25,5,000', '$26,5,000', '$27,5,000', '$28,5,000', '$29,5,000',
       '$30,5,000', '$31,5,000', '$32,5,000', '$33,5,000', '$34,5,000',
       '$35,5,000', '$36,5,000', '$37,5,000', '$39,5,000', '$40,5,000'],
      dtype=object)

In [ ]:
# handling salary column
df["salary"] = df["salary"].str.replace("$", "")
df["salary"] = df["salary"].str.replace(",", "")
df["salary"] = df["salary"].astype(int)
df["salary"].unique()

array([ 30000,  35000,  40000,  45000,  50000,  55000,  60000,  65000,
        75000,  85000,  95000, 105000, 115000, 125000, 135000, 145000,
       155000, 165000, 175000, 185000, 195000, 205000, 225000, 235000,
       245000, 255000, 265000, 275000, 285000, 295000, 305000, 315000,
       325000, 335000, 345000, 355000, 365000, 375000, 395000, 405000])

In [ ]:
df["date updated"].unique()

array(['2021-07-14'], dtype=object)

In [ ]:
df["date created"].unique()

array(['2012-03-04', '2020-02-01'], dtype=object)

In [ ]:
df.reset_index(inplace=True)
df = df.drop("index",axis=1)
df

,S.No.,president,prior,party,vice_president,salary,date updated,date created
0,1,John Quincy Adams,8th United States Secretary of State (1817â...,Democratic-Republican,John C. Calhoun,30000,2021-07-14,2012-03-04
1,2,Andrew Jackson,U.S. Senator ( Class 2 ) from Tennessee ...,Democratic,John C. Calhoun,35000,2021-07-14,2012-03-04
2,3,Martin Van Buren,8th Vice President of the United States,Democratic,Richard Mentor Johnson,40000,2021-07-14,2012-03-04
3,4,William Henry Harrison,United States Minister to Colombia (1828–1...,Whig,John Tyler,45000,2021-07-14,2012-03-04
4,5,John Tyler,10th Vice President of the United States,Whig,Office vacant,50000,2021-07-14,2012-03-04
5,6,James K. Polk,9th Governor of Tennessee (1839–1841),Democratic,George M. Dallas,55000,2021-07-14,2012-03-04
6,7,Zachary Taylor,Major General of the 1st Infantry Regiment ...,Whig,Millard Fillmore,60000,2021-07-14,2012-03-04
7,8,Millard Fillmore,12th Vice President of the United States,Whig,Office vacant,65000,2021-07-14,2012-03-04
8,9,Franklin Pierce,Brigadier General of the 9th Infantry Unit...,Democratic,William R. King,75000,2021-07-14,2012-03-04
9,10,James Buchanan,United States Minister to the Court of St J...,Democratic,John C. Breckinridge,85000,2021-07-14,2012-03-04


In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 41 entries, 0 to 40
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype 
---  ------          --------------  ----- 
 0   S.No.           41 non-null     int64 
 1   president       41 non-null     object
 2   prior           41 non-null     object
 3   party           41 non-null     object
 4   vice_president  41 non-null     object
 5   salary          41 non-null     int64 
 6   date updated    41 non-null     object
 7   date created    41 non-null     object
dtypes: int64(2), object(6)
memory usage: 2.7+ KB
