<a href="https://colab.research.google.com/github/hasinikondle/DataScience_Task/blob/main/numpy_task.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy Task

Part 1: Creating and Reshaping Arrays

1. Create Arrays:

o Create two NumPy arrays:

▪ A 1D array of 10 equally spaced values between 0 and 50.

▪ A 2D array of shape (3x3) containing random integers
between 5 and 20.

2. Array Dimensions:

o Print the dimensions of both arrays.

o Print the shape of both arrays.

3. Reshaping:

o Reshape the 1D array into a 2D array with shape (2x5).

o Print the reshaped array.

o Flatten the reshaped array
 back to 1D and print it.

In [92]:
# importing numpy library
import numpy as np

In [93]:
# creating and reshaping Arrays
# 1.create arrays
# A 1D array of 10 equally spaced values between 0 and 50.
arr1 = np.linspace(0,50,10)
arr1


array([ 0.        ,  5.55555556, 11.11111111, 16.66666667, 22.22222222,
       27.77777778, 33.33333333, 38.88888889, 44.44444444, 50.        ])

In [94]:
# A 2D array of shape (3x3) containing random integers between 5 and 20.
arr = np.random.randint(5,20,(3,3))
arr.reshape(3,3)


array([[15, 11, 12],
       [18, 19, 18],
       [ 6, 19, 17]])

In [95]:
# 2)print dimensions of both arrays
arr.ndim



2

In [96]:
arr1.ndim

1

In [97]:
# Print the shape of both arrays.
arr.shape



(3, 3)

In [98]:
arr1.shape

(10,)

In [99]:
# 3) reshape the 1D array into 2D
# Reshape the 1D array into a 2D array with shape (2x5).
# print the reshaped array
arr1 = arr1.reshape(2,5)
arr1

array([[ 0.        ,  5.55555556, 11.11111111, 16.66666667, 22.22222222],
       [27.77777778, 33.33333333, 38.88888889, 44.44444444, 50.        ]])

In [100]:
# Flatten the reshaped array back to 1D and print it.
arr1 = arr1.reshape(-1)
arr1.shape

(10,)

Part 2: Indexing and Slicing
5. Slicing:

o Slice the first four elements from the flattened 1D array.

o Reverse the elements of the 1D array using slicing.


In [101]:
#part - 2

#slicing
# Slice the first four elements from the flattened 1D array.
arr[0:4]


array([[15, 11, 12],
       [18, 19, 18],
       [ 6, 19, 17]])

In [102]:
# Reverse the elements of the 1D array using slicing.
arr[::-1]

array([[ 6, 19, 17],
       [18, 19, 18],
       [15, 11, 12]])

Part 3: Array Operations

6. Array Arithmetic:

o Create another 1D array of 10 integers between 1 and 10.

o Perform the following element-wise operations between the 1D
arrays created in Part 1 and Part 3:

▪ Addition

▪ Multiplication

▪ Subtract a constant value (e.g., 5) from the array.

In [103]:
#part-3
# Create another 1D array of 10 integers between 1 and 10.
arr2 = np.arange(1,11)
arr2
print(arr1)
print(arr2)


[ 0.          5.55555556 11.11111111 16.66666667 22.22222222 27.77777778
 33.33333333 38.88888889 44.44444444 50.        ]
[ 1  2  3  4  5  6  7  8  9 10]


In [104]:
# Perform the following element-wise operations between the 1D
# arrays created in Part 1 and Part 3:
# ▪ Addition
# ▪ Multiplication
# ▪ Subtract a constant value (e.g., 5) from the array.

# addition:
arr1+arr2

array([ 1.        ,  7.55555556, 14.11111111, 20.66666667, 27.22222222,
       33.77777778, 40.33333333, 46.88888889, 53.44444444, 60.        ])

In [105]:
# multiplication:
arr1*arr2

array([  0.        ,  11.11111111,  33.33333333,  66.66666667,
       111.11111111, 166.66666667, 233.33333333, 311.11111111,
       400.        , 500.        ])

In [106]:
# subtract a constant value:
arr1-5

array([-5.        ,  0.55555556,  6.11111111, 11.66666667, 17.22222222,
       22.77777778, 28.33333333, 33.88888889, 39.44444444, 45.        ])

Part 4: Random Number Generation and Copying

7. Random Numbers:

o Create a 1D array of 5 random values between 0 and 1.

o Create another 1D array of 5 random values between -1 and 1.

In [107]:
#part - 4
# Create a 1D array of 5 random values between 0 and 1.
np.random.rand(5)

array([0.35629322, 0.63391142, 0.12453702, 0.61261457, 0.23813464])

In [108]:
# Create another 1D array of 5 random values between -1 and 1.
np.random.randint(-1,1,5)

array([-1, -1, -1, -1,  0])

Part 5: Bonus

8. Challenge Task:

o Write a program that asks the user to input a number (n), and then
generates an n x n array of random integers between 1 and 100.

o Find the sum of all the elements in the array and print the result.

In [109]:
#part - 5
# Write a program that asks the user to input a number (n), and then
# generates an n x n array of random integers between 1 and 100


n = int(input("Enter n: "))
array = np.random.randint(1,101,(n,n))
print(array)
print(array.shape)

Enter n: 4
[[ 92   3  46  92]
 [ 48   9  78  31]
 [ 83  73  76  63]
 [ 92 100  85  75]]
(4, 4)


In [110]:
# Find the sum of all the elements in the array and print the result.
print("sum is :",np.sum(array))

sum is : 1046
